-- Migration: reminder delivery history
-- Table:     CONFROOM.NOTIFICATION_REMINDER_LOG  (new)
-- Date:      2026-07-29
--
-- Purpose
-- -------
-- Requirement 4 asks that a single request not generate duplicate notifications
-- during the same reminder interval, that failures be logged and retryable, and
-- that the workflow be safe when multiple scheduler instances run concurrently.
--
-- None of that was possible before: cfcs/scheduledAPI.cfc:sendPendingRequestReminder
-- kept no record of what it had sent, so two overlapping scheduler runs -- or one
-- run retried after a partial failure -- both re-mailed every administrator.
-- An inventory of the existing %NOTIF% tables found nothing recording per-recipient
-- reminder sends.
--
-- How duplicate suppression works
-- -------------------------------
-- Each send is bucketed by INTERVAL_KEY, a truncated timestamp derived from the
-- DATABASE clock (not the application server's), so several schedulers with
-- skewed clocks still agree on the bucket.
--
-- UQ_REMINDER_ONCE_PER_INTERVAL is the actual safety mechanism. The job INSERTs
-- its claim row BEFORE sending. If another instance already claimed that
-- (recipient, type, interval), the insert violates the constraint and raises
-- ORA-00001, which the job treats as "already handled, skip". This is atomic in
-- the database, so it holds across processes and servers -- something an
-- application-level <cflock> cannot do.
--
-- Retry safety: a row left in PENDING or marked FAILED can be retried. Rows
-- marked SENT are never re-sent for that interval.
--
-- Indexes
-- -------
-- Only two, both justified by the queries the job actually runs:
--   * UQ_REMINDER_ONCE_PER_INTERVAL - required for correctness, not speed.
--   * IDX_REMINDER_LOG_SENT_AT      - supports the retention/cleanup sweep and
--                                     "what went out recently" troubleshooting,
--                                     both of which filter on SENT_AT.
-- No index on BOOKING_ID: nothing queries by it today. Add one only if a
-- per-request history view is built and query analysis supports it.
--
-- Apply
-- -----
--   sqlplus CONFROOM/<password>@<tns> @add_notification_reminder_log.sql

CREATE TABLE NOTIFICATION_REMINDER_LOG (
    LOG_ID            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RECIPIENT_USER_ID NUMBER NOT NULL,
    NOTIFICATION_TYPE VARCHAR2(50) NOT NULL,
    -- Bucket this send belongs to, e.g. '2026-07-29 14' for an hourly cadence.
    INTERVAL_KEY      VARCHAR2(20) NOT NULL,
    -- Optional: set when a reminder concerns one specific request. The pending
    -- digest covers many, so it is left NULL there.
    BOOKING_ID        NUMBER,
    PENDING_COUNT     NUMBER,
    DELIVERY_STATUS   VARCHAR2(20) DEFAULT 'PENDING'
        CHECK (DELIVERY_STATUS IN ('PENDING','SENT','FAILED')),
    FAILURE_DETAIL    VARCHAR2(1000),
    CLAIMED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SENT_AT           TIMESTAMP,
    CONSTRAINT UQ_REMINDER_ONCE_PER_INTERVAL
        UNIQUE (RECIPIENT_USER_ID, NOTIFICATION_TYPE, INTERVAL_KEY),
    CONSTRAINT FK_REMINDER_LOG_USER
        FOREIGN KEY (RECIPIENT_USER_ID) REFERENCES USERS(USER_ID)
);

CREATE INDEX IDX_REMINDER_LOG_SENT_AT ON NOTIFICATION_REMINDER_LOG(SENT_AT);

COMMENT ON TABLE NOTIFICATION_REMINDER_LOG IS
    'One row per reminder notification per recipient per interval. The unique constraint is what prevents duplicate sends when scheduler runs overlap.';
COMMENT ON COLUMN NOTIFICATION_REMINDER_LOG.INTERVAL_KEY IS
    'Reminder bucket derived from the database clock, so concurrent schedulers with skewed clocks agree.';
COMMENT ON COLUMN NOTIFICATION_REMINDER_LOG.DELIVERY_STATUS IS
    'PENDING = claimed but not confirmed sent (safe to retry). SENT = delivered. FAILED = attempt failed, see FAILURE_DETAIL, safe to retry.';

COMMIT;

-- Verification
--   SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE FROM USER_CONSTRAINTS
--    WHERE TABLE_NAME = 'NOTIFICATION_REMINDER_LOG';
--   Expect UQ_REMINDER_ONCE_PER_INTERVAL (U), FK_REMINDER_LOG_USER (R), plus the PK.


-- ---------------------------------------------------------------------------
-- Retention (optional)
-- ---------------------------------------------------------------------------
-- This table grows by (number of administrators) rows per reminder interval.
-- At hourly cadence with 5 admins that is ~44k rows/year -- small, but a
-- periodic sweep keeps it tidy. Deleting history only loses the audit trail; it
-- cannot cause a duplicate send for any interval still in the future.
--
--   DELETE FROM NOTIFICATION_REMINDER_LOG WHERE SENT_AT < SYSDATE - 180;
--   COMMIT;


-- ---------------------------------------------------------------------------
-- ROLLBACK
-- ---------------------------------------------------------------------------
-- Dropping this table discards the reminder audit trail and re-enables duplicate
-- sends when scheduler runs overlap. The application code degrades safely: with
-- the table absent, sendPendingRequestReminder logs the failure and falls back to
-- sending without duplicate suppression, so reminders keep working but can double
-- up. Revert cfcs/scheduledAPI.cfc alongside this if that is not acceptable.
--
--   DROP TABLE NOTIFICATION_REMINDER_LOG CASCADE CONSTRAINTS;
--   COMMIT;
