-- ========================================
-- Recurring Bookings System Migration
-- Date: 2025-10-14
-- Purpose: Add recurring/repeating reservation functionality
-- ========================================

-- Create RECURRING_PATTERNS table
CREATE TABLE RECURRING_PATTERNS (
    PATTERN_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PARENT_BOOKING_ID NUMBER NOT NULL,
    FREQUENCY VARCHAR2(20) NOT NULL CHECK (FREQUENCY IN ('DAILY', 'WEEKLY', 'MONTHLY')),
    INTERVAL_COUNT NUMBER DEFAULT 1 NOT NULL CHECK (INTERVAL_COUNT > 0),
    END_TYPE VARCHAR2(20) NOT NULL CHECK (END_TYPE IN ('DATE', 'OCCURRENCES')),
    END_DATE DATE NULL,
    MAX_OCCURRENCES NUMBER NULL CHECK (MAX_OCCURRENCES > 0),
    DAYS_OF_WEEK VARCHAR2(50) NULL, -- Comma-separated: MON,WED,FRI
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT CHK_END_TYPE_VALUES CHECK (
        (END_TYPE = 'DATE' AND END_DATE IS NOT NULL) OR
        (END_TYPE = 'OCCURRENCES' AND MAX_OCCURRENCES IS NOT NULL)
    )
);

-- Create SYSTEM_SETTINGS table for recurring booking controls
CREATE TABLE SYSTEM_SETTINGS (
    SETTING_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SETTING_KEY VARCHAR2(100) UNIQUE NOT NULL,
    SETTING_VALUE VARCHAR2(500) NOT NULL,
    SETTING_TYPE VARCHAR2(20) NOT NULL CHECK (SETTING_TYPE IN ('BOOLEAN', 'NUMBER', 'STRING', 'DATE')),
    DESCRIPTION VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Add recurring-related columns to BOOKINGS table
ALTER TABLE BOOKINGS ADD (
    PARENT_BOOKING_ID NUMBER NULL,
    SERIES_INSTANCE_NUMBER NUMBER NULL,
    IS_RECURRING VARCHAR2(1) DEFAULT 'N' CHECK (IS_RECURRING IN ('Y', 'N'))
);

-- Add recurring-related column to ROOMS table
ALTER TABLE ROOMS ADD (
    RECURRING_ENABLED VARCHAR2(1) DEFAULT 'Y' CHECK (RECURRING_ENABLED IN ('Y', 'N'))
);

-- Add foreign key constraints
ALTER TABLE RECURRING_PATTERNS ADD CONSTRAINT FK_RECURRING_PARENT_BOOKING
    FOREIGN KEY (PARENT_BOOKING_ID) REFERENCES BOOKINGS(BOOKING_ID) ON DELETE CASCADE;

ALTER TABLE BOOKINGS ADD CONSTRAINT FK_BOOKINGS_PARENT
    FOREIGN KEY (PARENT_BOOKING_ID) REFERENCES BOOKINGS(BOOKING_ID) ON DELETE CASCADE;

-- Create indexes for performance
CREATE INDEX IDX_RECURRING_PARENT_BOOKING ON RECURRING_PATTERNS(PARENT_BOOKING_ID);
CREATE INDEX IDX_BOOKINGS_PARENT_ID ON BOOKINGS(PARENT_BOOKING_ID);
CREATE INDEX IDX_BOOKINGS_IS_RECURRING ON BOOKINGS(IS_RECURRING);
CREATE INDEX IDX_RECURRING_FREQUENCY ON RECURRING_PATTERNS(FREQUENCY);
CREATE INDEX IDX_SYSTEM_SETTINGS_KEY ON SYSTEM_SETTINGS(SETTING_KEY);

-- Add comments to document columns
COMMENT ON TABLE RECURRING_PATTERNS IS 'Stores recurring booking patterns and rules';
COMMENT ON TABLE SYSTEM_SETTINGS IS 'System-wide configuration settings for recurring bookings and other features';

COMMENT ON COLUMN RECURRING_PATTERNS.PARENT_BOOKING_ID IS 'References the parent/original booking that defines the series';
COMMENT ON COLUMN RECURRING_PATTERNS.FREQUENCY IS 'How often the booking repeats: DAILY, WEEKLY, or MONTHLY';
COMMENT ON COLUMN RECURRING_PATTERNS.INTERVAL_COUNT IS 'Interval between occurrences (e.g., 2 for every 2 weeks)';
COMMENT ON COLUMN RECURRING_PATTERNS.END_TYPE IS 'How the series ends: by DATE or after number of OCCURRENCES';
COMMENT ON COLUMN RECURRING_PATTERNS.END_DATE IS 'Final date for recurring bookings (used when END_TYPE = DATE)';
COMMENT ON COLUMN RECURRING_PATTERNS.MAX_OCCURRENCES IS 'Maximum number of occurrences (used when END_TYPE = OCCURRENCES)';
COMMENT ON COLUMN RECURRING_PATTERNS.DAYS_OF_WEEK IS 'For weekly patterns: comma-separated days (MON,TUE,WED,THU,FRI,SAT,SUN)';

COMMENT ON COLUMN BOOKINGS.PARENT_BOOKING_ID IS 'For recurring bookings: references the parent booking. NULL for standalone bookings';
COMMENT ON COLUMN BOOKINGS.SERIES_INSTANCE_NUMBER IS 'For recurring bookings: the instance number in the series (1, 2, 3, etc.)';
COMMENT ON COLUMN BOOKINGS.IS_RECURRING IS 'Y if this booking is part of a recurring series, N otherwise';

COMMENT ON COLUMN ROOMS.RECURRING_ENABLED IS 'Y if recurring bookings are allowed for this room, N to disable';

COMMENT ON COLUMN SYSTEM_SETTINGS.SETTING_KEY IS 'Unique key for the setting (e.g., MAX_RECURRING_OCCURRENCES)';
COMMENT ON COLUMN SYSTEM_SETTINGS.SETTING_VALUE IS 'The value of the setting as a string';
COMMENT ON COLUMN SYSTEM_SETTINGS.SETTING_TYPE IS 'Data type of the setting: BOOLEAN, NUMBER, STRING, or DATE';

-- Insert default system settings for recurring bookings
INSERT INTO SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION) VALUES
('RECURRING_SYSTEM_ENABLED', 'Y', 'BOOLEAN', 'Global toggle to enable/disable recurring booking system');

INSERT INTO SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION) VALUES
('MAX_RECURRING_OCCURRENCES', '52', 'NUMBER', 'Maximum number of recurring instances allowed (default 52 weeks/1 year)');

INSERT INTO SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION) VALUES
('MAX_RECURRING_MONTHS_AHEAD', '6', 'NUMBER', 'Maximum number of months ahead recurring bookings can be created');

INSERT INTO SYSTEM_SETTINGS (SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION) VALUES
('RECURRING_REQUIRE_APPROVAL', 'Y', 'BOOLEAN', 'Whether recurring bookings require admin approval');

COMMIT;

-- ========================================
-- Rollback Script (if needed)
-- ========================================
-- To rollback this migration, run:
/*
-- Drop constraints first
ALTER TABLE RECURRING_PATTERNS DROP CONSTRAINT FK_RECURRING_PARENT_BOOKING;
ALTER TABLE BOOKINGS DROP CONSTRAINT FK_BOOKINGS_PARENT;

-- Drop indexes
DROP INDEX IDX_RECURRING_PARENT_BOOKING;
DROP INDEX IDX_BOOKINGS_PARENT_ID;
DROP INDEX IDX_BOOKINGS_IS_RECURRING;
DROP INDEX IDX_RECURRING_FREQUENCY;
DROP INDEX IDX_SYSTEM_SETTINGS_KEY;

-- Drop columns from existing tables
ALTER TABLE BOOKINGS DROP COLUMN PARENT_BOOKING_ID;
ALTER TABLE BOOKINGS DROP COLUMN SERIES_INSTANCE_NUMBER;
ALTER TABLE BOOKINGS DROP COLUMN IS_RECURRING;
ALTER TABLE ROOMS DROP COLUMN RECURRING_ENABLED;

-- Drop tables
DROP TABLE RECURRING_PATTERNS;
DROP TABLE SYSTEM_SETTINGS;

COMMIT;
*/
