-- cfcs_schema.sql
-- Generated from analysis of DoCMRoomReservation/cfcs ColdFusion components
-- Target platform: Oracle Database (CONFROOM schema)

/***************************************************************************
 * ROLES
 ***************************************************************************/
CREATE TABLE roles (
    role_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name      VARCHAR2(50)   NOT NULL,
    role_description VARCHAR2(255)
);

CREATE UNIQUE INDEX roles_uq_name ON roles (LOWER(role_name));

/***************************************************************************
 * USERS
 * Referenced in Authenticate.cfc, dashboard-data.cfc, scheduledAPI.cfc
 ***************************************************************************/
CREATE TABLE users (
    user_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emplid         NUMBER(10)      NOT NULL,
    username       VARCHAR2(120),
    first_name     VARCHAR2(120)   NOT NULL,
    last_name      VARCHAR2(120)   NOT NULL,
    name_display   VARCHAR2(240),
    email          VARCHAR2(240)   NOT NULL,
    work_phone     VARCHAR2(40),
    office_loc     VARCHAR2(80),
    jobcode        VARCHAR2(40),
    jobtitle       VARCHAR2(160),
    divisionid     VARCHAR2(40),
    deptid         VARCHAR2(40),
    role_id        NUMBER          NOT NULL,
    status         VARCHAR2(20)    DEFAULT 'NEW' NOT NULL,
    dateentered    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    enteredbyid    NUMBER,
    datemodified   TIMESTAMP,
    modifiedbyid   NUMBER,
    lastloggedon   TIMESTAMP,
    is_admin       NUMBER(1)       DEFAULT 0,
    UNIQUE (emplid)
);

ALTER TABLE users
    ADD CONSTRAINT fk_users_roles
        FOREIGN KEY (role_id) REFERENCES roles(role_id);

CREATE INDEX users_idx_status ON users(status);
CREATE INDEX users_idx_role ON users(role_id);

/***************************************************************************
 * ROOMS
 * Referenced across Room.cfc and dashboard-data.cfc
 ***************************************************************************/
CREATE TABLE rooms (
    room_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_name          VARCHAR2(150) NOT NULL,
    building           VARCHAR2(80)  NOT NULL,
    room_number        VARCHAR2(40)  NOT NULL,
    dept_id            VARCHAR2(40),
    location           VARCHAR2(120),
    capacity           NUMBER        DEFAULT 1,
    telecom_type       VARCHAR2(60),
    videoconf          NUMBER(1)     DEFAULT 0,
    clickshare         NUMBER(1)     DEFAULT 0,
    computer           NUMBER(1)     DEFAULT 0,
    phone              NUMBER(1)     DEFAULT 0,
    camera             NUMBER(1)     DEFAULT 0,
    keyboard_mouse     NUMBER(1)     DEFAULT 0,
    docking_station    NUMBER(1)     DEFAULT 0,
    monitors           NUMBER        DEFAULT 0,
    room_type          VARCHAR2(60),
    has_door           NUMBER(1)     DEFAULT 1,
    floor              VARCHAR2(20),
    room_description   CLOB,
    equipment          CLOB,
    comments           CLOB,
    maintenance_status VARCHAR2(40)  DEFAULT 'Available',
    maintenance        VARCHAR2(3)   DEFAULT 'NO',
    recurring          VARCHAR2(3)   DEFAULT 'NO',
    status             VARCHAR2(20)  DEFAULT 'ACTIVE',
    room_image         BLOB,
    enteredbyid        NUMBER,
    dateentered        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modifiedbyid       NUMBER,
    datemodified       TIMESTAMP
);

CREATE INDEX rooms_idx_status ON rooms(status);
CREATE INDEX rooms_idx_building ON rooms(building, room_number);

/***************************************************************************
 * AMENITIES & ROOM_AMENITIES (dashboard-data.cfc getRoom)
 ***************************************************************************/
CREATE TABLE amenities (
    amenity_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amenity_name    VARCHAR2(120) NOT NULL,
    amenity_type    VARCHAR2(60)
);

CREATE TABLE room_amenities (
    room_id     NUMBER NOT NULL,
    amenity_id  NUMBER NOT NULL,
    PRIMARY KEY (room_id, amenity_id),
    FOREIGN KEY (room_id) REFERENCES rooms(room_id),
    FOREIGN KEY (amenity_id) REFERENCES amenities(amenity_id)
);

/***************************************************************************
 * BOOKINGS
 * Used in dashboard-data.cfc and scheduledAPI.cfc
 ***************************************************************************/
CREATE TABLE bookings (
    booking_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             NUMBER      NOT NULL,
    room_id             NUMBER      NOT NULL,
    start_time          TIMESTAMP   NOT NULL,
    end_time            TIMESTAMP   NOT NULL,
    status              VARCHAR2(20) DEFAULT 'pending',
    comments            CLOB,
    recurring_details   VARCHAR2(4000),
    recurring           VARCHAR2(5) DEFAULT 'NO',
    meeting_title       VARCHAR2(255),
    approved_by         NUMBER,
    notification_sent   NUMBER(1) DEFAULT 0,
    end_notification_sent NUMBER(1) DEFAULT 0,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP,
    bookingdate         DATE,            -- legacy support (dashboard-data)
    starttime           DATE,            -- legacy support
    endtime             DATE,
    UNIQUE (room_id, start_time, end_time)
);

ALTER TABLE bookings
    ADD CONSTRAINT fk_bookings_user
        FOREIGN KEY (user_id) REFERENCES users(user_id);

ALTER TABLE bookings
    ADD CONSTRAINT fk_bookings_room
        FOREIGN KEY (room_id) REFERENCES rooms(room_id);

ALTER TABLE bookings
    ADD CONSTRAINT fk_bookings_approver
        FOREIGN KEY (approved_by) REFERENCES users(user_id);

CREATE INDEX bookings_idx_status ON bookings(status);
CREATE INDEX bookings_idx_user ON bookings(user_id);
CREATE INDEX bookings_idx_room_time ON bookings(room_id, start_time, end_time);

/***************************************************************************
 * NOTIFICATION SUPPORT (optional but referenced indirectly)
 ***************************************************************************/
CREATE TABLE notifications (
    notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER       NOT NULL,
    type            VARCHAR2(80) NOT NULL,
    content         CLOB         NOT NULL,
    status          VARCHAR2(20) DEFAULT 'Unread',
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    modified_at     TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE INDEX notifications_idx_user ON notifications(user_id, status);

/***************************************************************************
 * DEPARTMENTS (Room.cfc getDepartments)
 ***************************************************************************/
CREATE TABLE departments (
    department_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name    VARCHAR2(150) NOT NULL,
    division_name      VARCHAR2(150),
    division_id        VARCHAR2(40)
);

/***************************************************************************
 * SAMPLE LOOKUP DATA
 ***************************************************************************/
INSERT INTO roles (role_name, role_description) VALUES ('Admin', 'Full administrative privileges');
INSERT INTO roles (role_name, role_description) VALUES ('Approver', 'Can approve booking requests');
INSERT INTO roles (role_name, role_description) VALUES ('User', 'Standard booking privileges');

COMMIT;
