-- ========================================
-- Room Reservation System Schema
-- ========================================
--
-- Reconciled against the live development schema (CONFROOM on inside2_docmd)
-- on 2026-07-29 by querying ALL_TAB_COLUMNS and ALL_CONSTRAINTS.
--
-- This file had drifted badly and was actively misleading: it described
-- SYSTEM_LOGS as ACTION/DETAILS/TIMESTAMP when the live columns are
-- ACTION_TYPE/CHANGE_DETAILS/LOG_TIMESTAMP, and BOOKINGS.STATUS as
-- CHECK (STATUS IN ('Confirmed','Cancelled')) when the live values are
-- pending/approved/rejected/cancelled/archived. It also would not run: the ROOMS
-- definition was missing a comma and AMENITIES was missing its terminating
-- semicolon. All of that is corrected below.
--
-- Columns added by later migrations are now folded in and marked with the
-- migration that owns them, so this file matches what a fresh environment needs:
--   * add_booking_revision_tracking.sql          -> BOOKINGS revision columns
--   * add_reservation_for_and_decision_audit.sql -> BOOKINGS booked-for + audit
--   * notification_preferences.sql               -> NOTIFICATION_TYPES / _PREFERENCES
--   * system_notification_controls.sql           -> notification control tables
--   * add_notification_reminder_log.sql          -> NOTIFICATION_REMINDER_LOG
-- Those files remain the migration path for existing environments; this file is
-- the consolidated picture.
--
-- KNOWN DRIFT STILL PRESENT IN THE LIVE SCHEMA (documented, not "fixed" here):
--   * BOOKINGS.APPROVED_BY has no foreign key in the live database, although
--     earlier versions of this file declared FK_BOOKINGS_APPROVED_BY.
--   * FK_BOOKINGS_ORIGINAL and FK_BOOKINGS_MODIFIED_BY are declared by
--     add_booking_revision_tracking.sql but are NOT present live, so that
--     migration's constraint statements never took effect.
--   * USERS.STATUS has no CHECK constraint live, though this file used to
--     declare one. Application code compares it case-insensitively as a result.
-- Verify against the target environment before relying on any of the above.

-- 1. ROLES
CREATE TABLE ROLES (
    ROLE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ROLE_NAME VARCHAR2(100) UNIQUE NOT NULL
);

-- 2. USERS
CREATE TABLE USERS (
    USER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    EMPLID NUMBER,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    ROLE_ID NUMBER,
    -- No CHECK constraint live. Code compares this case-insensitively
    -- (UPPER(u.STATUS) = 'ACTIVE') because the stored casing is not enforced.
    STATUS VARCHAR2(20),
    NOTIFICATION_PREFERENCES CLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EMPLID NUMBER(38),
    LASTLOGGEDON TIMESTAMP,
    DATEENTERED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ENTEREDBYID NUMBER(38),
    -- No default live, unlike DATEENTERED.
    DATEMODIFIED TIMESTAMP,
    MODIFIEDBYID NUMBER(38),
    CONSTRAINT FK_USERS_ROLES FOREIGN KEY (ROLE_ID)
        REFERENCES ROLES(ROLE_ID)
);

-- Seeded roles. Application code treats 'Admin' and 'Site Admin' as approvers.
-- INSERT INTO ROLES (ROLE_NAME) VALUES ('Site Admin');  -- ROLE_ID 1
-- INSERT INTO ROLES (ROLE_NAME) VALUES ('Admin');       -- ROLE_ID 2
-- INSERT INTO ROLES (ROLE_NAME) VALUES ('User');        -- ROLE_ID 3

-- 3. ROOMS
CREATE TABLE ROOMS (
    ROOM_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ROOM_NAME VARCHAR2(100) NOT NULL,
    BUILDING VARCHAR2(100) NOT NULL,
    ROOM_NUMBER NUMBER NOT NULL,
    CAPACITY NUMBER NOT NULL,
    DESCRIPTION VARCHAR2(500),
    -- VARCHAR2(3) with a 'NO' default live, and no CHECK constraint. The
    -- previous VARCHAR2(20) + CHECK definition here did not match, and the
    -- missing comma after it meant this file could not be executed at all.
    MAINTENANCE_STATUS VARCHAR2(3) DEFAULT 'NO',
    RECURRING VARCHAR2(3) DEFAULT 'NO',
    ROOM_IMAGE CLOB,
    STATUS VARCHAR2(10) DEFAULT 'Active'
);

-- 4. AMENITIES
CREATE TABLE AMENITIES (
    AMENITY_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AMENITY_NAME VARCHAR2(100) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR2(500),
    ICON_ID NUMBER,
    CONSTRAINT FK_AMENITIES_ICONS FOREIGN KEY (ICON_ID)
        REFERENCES ICONS(ICON_ID)
);
-- NOTE: this references ICONS, which is created at the end of this file. Create
-- ICONS before AMENITIES, or add the constraint afterwards.

-- 5. ROOM_AMENITIES (Join Table)
CREATE TABLE ROOM_AMENITIES (
    ROOM_ID NUMBER NOT NULL,
    AMENITY_ID NUMBER NOT NULL,
    PRIMARY KEY (ROOM_ID, AMENITY_ID),
    CONSTRAINT FK_ROOM_AMENITIES_ROOMS FOREIGN KEY (ROOM_ID)
        REFERENCES ROOMS(ROOM_ID),
    CONSTRAINT FK_ROOM_AMENITIES_AMENITIES FOREIGN KEY (AMENITY_ID)
        REFERENCES AMENITIES(AMENITY_ID)
);

-- 6. BOOKINGS
CREATE TABLE BOOKINGS (
    BOOKING_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Who SUBMITTED the request. Distinct from BOOKED_FOR_* below.
    USER_ID NUMBER NOT NULL,
    ROOM_ID NUMBER NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    RECURRING_DETAILS VARCHAR2(500),
    -- Values are lowercase. The old definition here claimed
    -- CHECK (STATUS IN ('Confirmed','Cancelled')), which matched nothing the
    -- application ever writes. Enforced live by CHK_BOOKINGS_STATUS.
    STATUS VARCHAR2(20),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    APPROVED_BY NUMBER(38),
    -- Holds the requester's meeting title / purpose. 1000 chars live, not 500.
    -- Approval must not overwrite this; see assets/cfc/approvals.cfc.
    COMMENTS VARCHAR2(1000),

    -- from add_booking_revision_tracking.sql
    ORIGINAL_BOOKING_ID NUMBER,
    REVISION_NUMBER NUMBER DEFAULT 0 NOT NULL,
    IS_MODIFIED CHAR(1) DEFAULT 'N' CHECK (IS_MODIFIED IN ('Y', 'N')),
    REVISION_DATE TIMESTAMP,
    MODIFIED_BY NUMBER,

    -- from add_reservation_for_and_decision_audit.sql
    -- "Reservation For": who the space is actually for. NULL on records created
    -- before this existed, and the application then falls back to the requester.
    BOOKED_FOR_NAME VARCHAR2(200),
    BOOKED_FOR_EMAIL VARCHAR2(255),
    BOOKED_FOR_DEPARTMENT VARCHAR2(100),
    DECIDED_AT TIMESTAMP,
    DECIDED_BY NUMBER,
    CANCELLED_AT TIMESTAMP,
    CANCELLED_BY NUMBER,
    CANCELLATION_REASON VARCHAR2(1000),

    CONSTRAINT CHK_BOOKINGS_STATUS CHECK
        (STATUS IN ('pending', 'approved', 'rejected', 'cancelled', 'archived')),
    CONSTRAINT FK_BOOKINGS_USERS FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),
    CONSTRAINT FK_BOOKINGS_ROOMS FOREIGN KEY (ROOM_ID)
        REFERENCES ROOMS(ROOM_ID),
    CONSTRAINT FK_BOOKINGS_CANCELLED_BY FOREIGN KEY (CANCELLED_BY)
        REFERENCES USERS(USER_ID),
    CONSTRAINT FK_BOOKINGS_DECIDED_BY FOREIGN KEY (DECIDED_BY)
        REFERENCES USERS(USER_ID)
    -- Deliberately NOT declared, to match the live database:
    --   FK_BOOKINGS_APPROVED_BY (APPROVED_BY -> USERS)
    --   FK_BOOKINGS_ORIGINAL    (ORIGINAL_BOOKING_ID -> BOOKINGS)
    --   FK_BOOKINGS_MODIFIED_BY (MODIFIED_BY -> USERS)
    -- The latter two are declared by add_booking_revision_tracking.sql but are
    -- absent live. Adding them to a new environment is reasonable; just be aware
    -- existing environments do not have them.
);

-- 7. NOTIFICATIONS
CREATE TABLE NOTIFICATIONS (
    NOTIFICATION_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    TYPE VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(1000),
    STATUS VARCHAR2(20) CHECK (STATUS IN ('Read', 'Unread')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_NOTIFICATIONS_USERS FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
);

-- 8. MAINTENANCE
CREATE TABLE MAINTENANCE (
    MAINTENANCE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ROOM_ID NUMBER NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    STATUS VARCHAR2(20) CHECK (STATUS IN ('Scheduled', 'In Progress', 'Completed')),
    CONSTRAINT FK_MAINTENANCE_ROOMS FOREIGN KEY (ROOM_ID)
        REFERENCES ROOMS(ROOM_ID)
);

-- 9. SYSTEM_LOGS
-- The previous definition here named these columns ACTION, DETAILS and
-- TIMESTAMP. None of those exist. Anything written against that definition fails
-- with ORA-00904; the live column names are below.
CREATE TABLE SYSTEM_LOGS (
    LOG_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER,
    ACTION_TYPE VARCHAR2(100) NOT NULL,
    CHANGE_DETAILS VARCHAR2(1000),
    LOG_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- Which table and row the entry concerns, e.g. 'BOOKINGS' / '4242'.
    TABLE_NAME VARCHAR2(100),
    RECORD_ID VARCHAR2(100),
    CONSTRAINT FK_SYSTEM_LOGS_USERS FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
);

--10 . ICONS
CREATE TABLE ICONS (
    ICON_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ICON_NAME VARCHAR2(100) UNIQUE NOT NULL,
    ICON_CLASS VARCHAR2(100) NOT NULL       -- CSS class for the icon (e.g., FontAwesome class)
);
-- ========================================
-- STORED PROCEDURES
-- ========================================

-- Procedure to log database changes
DELIMITER $$
CREATE PROCEDURE LogDatabaseChange(
    IN userId INT,
    IN actionType VARCHAR(100),
    IN tableName VARCHAR(100),
    IN recordId VARCHAR(255),
    IN changeDetails TEXT
)
BEGIN
    INSERT INTO SYSTEM_LOGS (
        USER_ID,
        ACTION,
        DETAILS,
        TIMESTAMP
    )
    VALUES (
        userId,
        actionType,
        CONCAT('Table: ', tableName, ', Record ID: ', recordId, ', Changes: ', changeDetails),
        CURRENT_TIMESTAMP
    );
END$$
DELIMITER ;

-- Procedure to add a room
DELIMITER $$
CREATE PROCEDURE AddRoom(
    IN roomName VARCHAR(100),
    IN building VARCHAR(100),
    IN floor INT,
    IN capacity INT,
    IN description VARCHAR(500),
    IN userId INT
)
BEGIN
    DECLARE newRoomId INT;

    -- Insert into ROOMS table
    INSERT INTO ROOMS (ROOM_NAME, BUILDING, ROOM_NUMBER, CAPACITY, DESCRIPTION)
    VALUES (roomName, building, floor, capacity, description);

    -- Retrieve the newly generated ROOM_ID
    SET newRoomId = LAST_INSERT_ID();

    -- Log the action in SYSTEM_LOGS
    CALL LogDatabaseChange(
        userId,
        'INSERT',
        'ROOMS',
        newRoomId,
        CONCAT('Room Name: ', roomName, ', Building: ', building, ', Floor: ', floor, ', Capacity: ', capacity, ', Description: ', description)
    );
END$$
DELIMITER ;

-- Procedure to update an amenity
DELIMITER $$
CREATE PROCEDURE UpdateAmenity(
    IN amenityId INT,
    IN amenityName VARCHAR(100),
    IN description VARCHAR(500),
    IN userId INT
)
BEGIN
    -- Update AMENITIES table
    UPDATE AMENITIES
    SET AMENITY_NAME = amenityName,
        DESCRIPTION = description
    WHERE AMENITY_ID = amenityId;

    -- Log the action in SYSTEM_LOGS
    CALL LogDatabaseChange(
        userId,
        'UPDATE',
        'AMENITIES',
        amenityId,
        CONCAT('Updated Amenity Name: ', amenityName, ', Description: ', description)
    );
END$$
DELIMITER ;

-- Procedure to add a booking
DELIMITER $$
CREATE PROCEDURE AddBooking(
    IN userId INT,
    IN roomId INT,
    IN startTime TIMESTAMP,
    IN endTime TIMESTAMP,
    IN recurringDetails VARCHAR(500)
)
BEGIN
    DECLARE newBookingId INT;

    -- Insert into BOOKINGS table
    INSERT INTO BOOKINGS (USER_ID, ROOM_ID, START_TIME, END_TIME, RECURRING_DETAILS, STATUS)
    VALUES (userId, roomId, startTime, endTime, recurringDetails, 'Confirmed');

    -- Retrieve the newly generated BOOKING_ID
    SET newBookingId = LAST_INSERT_ID();

    -- Log the action in SYSTEM_LOGS
    CALL LogDatabaseChange(
        userId,
        'INSERT',
        'BOOKINGS',
        newBookingId,
        CONCAT('Room ID: ', roomId, ', Start Time: ', startTime, ', End Time: ', endTime, ', Recurring: ', recurringDetails)
    );
END$$
DELIMITER ;

-- ========================================
-- Indexes for Performance Optimization
-- ========================================

-- Indexes on foreign keys
CREATE INDEX IDX_USERS_ROLE_ID ON USERS(ROLE_ID);
CREATE INDEX IDX_BOOKINGS_USER_ID ON BOOKINGS(USER_ID);
CREATE INDEX IDX_BOOKINGS_ROOM_ID ON BOOKINGS(ROOM_ID);
CREATE INDEX IDX_NOTIFICATIONS_USER_ID ON NOTIFICATIONS(USER_ID);
CREATE INDEX IDX_MAINTENANCE_ROOM_ID ON MAINTENANCE(ROOM_ID);
CREATE INDEX IDX_SYSTEM_LOGS_USER_ID ON SYSTEM_LOGS(USER_ID);

-- ========================================
-- Additional Constraints and Triggers (Optional)
-- ========================================

-- Example Trigger to update UPDATED_AT column on USERS table
CREATE OR REPLACE TRIGGER TRG_USERS_BEFORE_UPDATE
BEFORE UPDATE ON USERS
FOR EACH ROW
BEGIN
    :NEW.DATEMODIFIED := CURRENT_TIMESTAMP;
END;
/

-- Similarly, triggers can be created for other tables as needed.
-- ========================================
-- Sample Data (Optional)
-- ========================================

-- Insert sample roles
INSERT INTO ROLES (ROLE_NAME) VALUES ('Site Admin');
INSERT INTO ROLES (ROLE_NAME) VALUES ('Admin');
INSERT INTO ROLES (ROLE_NAME) VALUES ('User');

-- Insert sample icons
INSERT INTO ICONS (ICON_NAME, ICON_CLASS) VALUES ('Projector', 'fa fa-projector');
INSERT INTO ICONS (ICON_NAME, ICON_CLASS) VALUES ('Whiteboard', 'fa fa-whiteboard');
INSERT INTO ICONS (ICON_NAME, ICON_CLASS) VALUES ('Video Conferencing', 'fa fa-video');
INSERT INTO ICONS (ICON_NAME, ICON_CLASS) VALUES ('Phone', 'fa fa-phone');
INSERT INTO ICONS (ICON_NAME, ICON_CLASS) VALUES ('Camera', 'fa fa-camera');
INSERT INTO ICONS (ICON_NAME, ICON_CLASS) VALUES ('Clickshare', 'fa fa-map-pin');
INSERT INTO ICONS (ICON_NAME, ICON_CLASS) VALUES ('Computer', 'fa fa-computer');
INSERT INTO ICONS (ICON_NAME, ICON_CLASS) VALUES ('Keyboard and Mouse', 'fa fa-keyboard');
INSERT INTO ICONS (ICON_NAME, ICON_CLASS) VALUES ('Docking Station', 'fa fa-dock');
INSERT INTO ICONS (ICON_NAME, ICON_CLASS) VALUES ('Monitor', 'fa fa-tv');

-- Insert sample amenities
INSERT INTO AMENITIES (AMENITY_NAME, DESCRIPTION, ICON_ID) VALUES ('Projector', 'High-definition projector', 1);
INSERT INTO AMENITIES (AMENITY_NAME, DESCRIPTION, ICON_ID) VALUES ('Whiteboard', 'Wall-mounted whiteboard', 2);
INSERT INTO AMENITIES (AMENITY_NAME, DESCRIPTION, ICON_ID) VALUES ('Video Conferencing', 'Supports remote meetings', 3);
INSERT INTO AMENITIES (AMENITY_NAME, DESCRIPTION, ICON_ID) VALUES ('Phone', 'Desk phone', 4);
INSERT INTO AMENITIES (AMENITY_NAME, DESCRIPTION, ICON_ID) VALUES ('Camera', 'Camera for video conferencing', 5);
INSERT INTO AMENITIES (AMENITY_NAME, DESCRIPTION, ICON_ID) VALUES ('Clickshare', 'Supports clickshare', 6);
INSERT INTO AMENITIES (AMENITY_NAME, DESCRIPTION, ICON_ID) VALUES ('Computer', 'Desktop computer', 7);
INSERT INTO AMENITIES (AMENITY_NAME, DESCRIPTION, ICON_ID) VALUES ('Keyboard and Mouse', 'Keyboard and mouse', 8);
INSERT INTO AMENITIES (AMENITY_NAME, DESCRIPTION, ICON_ID) VALUES ('Docking Station', 'Laptop docking station', 9);
INSERT INTO AMENITIES (AMENITY_NAME, DESCRIPTION, ICON_ID) VALUES ('1 Monitor', 'One monitor for Desktop computer', 10);
INSERT INTO AMENITIES (AMENITY_NAME, DESCRIPTION, ICON_ID) VALUES ('2 Monitors', 'Two monitors for Desktop computer', 10);
INSERT INTO AMENITIES (AMENITY_NAME, DESCRIPTION, ICON_ID) VALUES ('3 Monitors', 'Three monitors for Desktop computer', 10);

INSERT INTO ROOMS (ROOM_NAME, BUILDING, ROOM_NUMBER, CAPACITY, DESCRIPTION) VALUES ('Library',        'FC-11', 2017, 8, 'Small conference room');
INSERT INTO ROOMS (ROOM_NAME, BUILDING, ROOM_NUMBER, CAPACITY, DESCRIPTION) VALUES ('Meeting Room',   'FC-11', 2019, 8, 'Small conference room');
INSERT INTO ROOMS (ROOM_NAME, BUILDING, ROOM_NUMBER, CAPACITY, DESCRIPTION) VALUES ('Conference Room','FC-11', 2037, 25, 'Large conference room');
INSERT INTO ROOMS (ROOM_NAME, BUILDING, ROOM_NUMBER, CAPACITY, DESCRIPTION) VALUES ('Focus Room 1',   'FC-11', 2006, 1, 'Office');
INSERT INTO ROOMS (ROOM_NAME, BUILDING, ROOM_NUMBER, CAPACITY, DESCRIPTION) VALUES ('Focus Room 2',   'FC-11', 2010, 1, 'Office');
INSERT INTO ROOMS (ROOM_NAME, BUILDING, ROOM_NUMBER, CAPACITY, DESCRIPTION) VALUES ('Focus Room 3',   'FC-11', 2012, 1, 'Office');
INSERT INTO ROOMS (ROOM_NAME, BUILDING, ROOM_NUMBER, CAPACITY, DESCRIPTION) VALUES ('Focus Room 4',   'FC-11', 2016, 1, 'Office');
INSERT INTO ROOMS (ROOM_NAME, BUILDING, ROOM_NUMBER, CAPACITY, DESCRIPTION) VALUES ('Focus Room 5',   'FC-11', 2021, 1, 'Office');
INSERT INTO ROOMS (ROOM_NAME, BUILDING, ROOM_NUMBER, CAPACITY, DESCRIPTION) VALUES ('Focus Room 6',   'FC-11', 2023, 1, 'Office');
INSERT INTO ROOMS (ROOM_NAME, BUILDING, ROOM_NUMBER, CAPACITY, DESCRIPTION) VALUES ('Focus Room 7',   'FC-11', 2030, 1, 'Office');
INSERT INTO ROOMS (ROOM_NAME, BUILDING, ROOM_NUMBER, CAPACITY, DESCRIPTION) VALUES ('Focus Room 8',   'FC-11', 2032, 1, 'Office');
INSERT INTO ROOMS (ROOM_NAME, BUILDING, ROOM_NUMBER, CAPACITY, DESCRIPTION) VALUES ('Focus Room 9',   'FC-11', 2036, 1, 'Office');
INSERT INTO ROOMS (ROOM_NAME, BUILDING, ROOM_NUMBER, CAPACITY, DESCRIPTION) VALUES ('Focus Room 10',  'FC-11', 2038, 1, 'Office');
INSERT INTO ROOMS (ROOM_NAME, BUILDING, ROOM_NUMBER, CAPACITY, DESCRIPTION) VALUES ('Focus Room 11',  'FC-11', 2042, 1, 'Office');
INSERT INTO ROOMS (ROOM_NAME, BUILDING, ROOM_NUMBER, CAPACITY, DESCRIPTION) VALUES ('Focus Room 12',  'FC-11', 2044, 1, 'Office');
INSERT INTO ROOMS (ROOM_NAME, BUILDING, ROOM_NUMBER, CAPACITY, DESCRIPTION) VALUES ('Focus Room 13',  'FC-11', 2048, 1, 'Office');
INSERT INTO ROOMS (ROOM_NAME, BUILDING, ROOM_NUMBER, CAPACITY, DESCRIPTION) VALUES ('Focus Room 14',  'FC-11', 2049, 1, 'Office');
INSERT INTO ROOMS (ROOM_NAME, BUILDING, ROOM_NUMBER, CAPACITY, DESCRIPTION) VALUES ('Focus Room 15',  'FC-11', 2052, 1, 'Office');
INSERT INTO ROOMS (ROOM_NAME, BUILDING, ROOM_NUMBER, CAPACITY, DESCRIPTION) VALUES ('Focus Room 16',  'FC-11', 2054, 1, 'Office');
 